routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->middleware('auth')->name('root');
Route::get('/home', 'HomeController@index')->middleware('auth')->name('home');

/**
 * USER
 */
Route::delete('/delete/{id}', 'HomeController@destroy')->middleware('admin');
Route::get('/edit/{id}', 'HomeController@edit')->middleware('admin');
Route::put('/update/{id}', 'HomeController@update')->middleware('admin');
Route::get('/users', 'HomeController@users')->middleware('admin')->name('user_list');
Route::get('/users/vue', 'HomeController@users_vue')->middleware('admin');
/**
 * END USER
 */
Route::group(['prefix' => 'admin'], function () {
    Route::get('/', function () {
        return redirect()->route('sign-in-admin');
    })->middleware('admin_guest');
    Route::get('/logout', 'AdminController@logout')->middleware('admin')->name('log-out-admin');

    Route::group(['middleware' => 'admin_guest'], function (){
        Route::get('/login', 'AdminController@login')->name('sign-in-admin');
        Route::post('/login', 'AdminController@loginPostAction')->name('sign-in-admin-post');
        Route::get('/register', 'AdminController@register')->name('sign-up-admin');
        Route::post('/register', 'AdminController@registerPostAction')->name('sign-up-admin-post');
    });

});

Route::group(['prefix' => 'auth'], function () {
    Route::get('/', function () {
        return redirect()->route('sign-in');
    });
    Route::get('/sign-up', 'AuthController@register')->middleware('guest')->name('sign-up');
    Route::post('/sign-up', 'AuthController@registerPostAction')->middleware('guest')->name('sign-up-post');

    Route::get('/sign-in', 'AuthController@login')->middleware('guest')->name('login');
    Route::post('/sign-in', 'AuthController@loginPostAction')->middleware('guest')->name('sign-in-post');

    Route::get('/log-out', 'AuthController@logout')->middleware('auth')->name('log-out');
});

Route::resource('product','ProductController')->middleware('auth');

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class ProductController extends Controller
{

    public function index()
    {
        $data = [
          'title' => 'Product List'
        ];
        return view('product.v_product_index', $data);
    }

    public function create()
    {
        $data = [
            'title' => 'Add Product'
        ];
        return view('product.v_product_add', $data);
    }

    public function store(Request $request)
    {
        dd($request->all());
    }

    public function show($id)
    {
        //
    }

    public function edit($id)
    {
        //
    }

    public function update(Request $request, $id)
    {
        //
    }

    public function destroy($id)
    {
        //
    }
}

resources/views/product/v_product_add.blade.php
@extends('layouts.v_layouts_home')

@section('title',  $title)

@section('content')
    <div class="jumbotron jumbotron-fluid">
        <div class="container">
            <h1 class="display-4">{{ $title }}</h1>
            <p class="lead">Add your best products.</p>
        </div>
    </div>
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="row justify-content-center">
                <div class="col-md-8">
                    @if (session('messages'))
                        {!! session('messages') !!}
                    @endif
                        <div class="card">
                            <div class="card-body">
                                <form action="{{ route('product.store') }}" method="post" enctype="multipart/form-data">
                                    {{ csrf_field() }}
                                    <div class="form-group">
                                        <label for="InputName">Product Name</label>
                                        <input type="text" value="{{ old('name') }}"
                                               class="form-control @error('name') is-invalid @enderror" name="name" id="InputName">
                                        @error('name')
                                        <small class="text-danger">{{ $message }}</small>
                                        @enderror
                                    </div>
                                    <div class="form-group">
                                        <label>Product Short Description</label>
                                        <input type="text" value="{{ old('short_description') }}"
                                               class="form-control @error('short_description') is-invalid @enderror" name="short_description">
                                        @error('short_description')
                                        <small class="text-danger">{{ $message }}</small>
                                        @enderror
                                    </div>
                                    <div class="form-group">
                                        <label>Product Description</label>
                                        <input type="text" value="{{ old('description') }}"
                                               class="form-control @error('description') is-invalid @enderror" name="description">
                                        @error('description')
                                        <small class="text-danger">{{ $message }}</small>
                                        @enderror
                                    </div>
                                    <div class="form-group">
                                        <label>Product Price</label>
                                        <input type="number" value="{{ old('price') }}"
                                               class="form-control @error('price') is-invalid @enderror" name="price" step="1000">
                                        @error('price')
                                        <small class="text-danger">{{ $message }}</small>
                                        @enderror
                                    </div>
                                    <div class="form-group">
                                        <label for="InputImage">Product Image</label>
                                        <input type="file" class="form-control @error('image') is-invalid @enderror" name="image" id="InputImage">
                                        @error('image')
                                        <small class="text-danger">{{ $message }}</small>
                                        @enderror
                                    </div>
                                    <div class="row justify-content-center">
                                        <button type="submit" class="btn btn-primary align-center">Submit</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/product/v_product_index.blade.php
@extends('layouts.v_layouts_home')

@section('title',  $title)

@section('content')
    <div class="jumbotron jumbotron-fluid">
        <div class="container">
            <h1 class="display-4">{{ $title }} <span class="text-primary">{{ config('app.name') }}</span></h1>
            <p class="lead">Here your garbage products.</p>
        </div>
    </div>
    <div class="row justify-content-center">
        <div class="col-md-8">
            @if (session('messages'))
                {!! session('messages') !!}
            @endif
            <table class="table">
                <thead class="thead-light">
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Name</th>
                    <th scope="col">Email</th>
                    <th scope="col">Created At</th>
                    <th class="text-center" scope="col">Actions</th>
                </tr>
                </thead>
                <tbody>
{{--                @foreach ($users as $user)--}}
{{--                    <tr>--}}
{{--                        <th scope="row">{{ $user['id'] }}</th>--}}
{{--                        <td>{{ $user['name'] }}</td>--}}
{{--                        <td>{{ $user['email'] }}</td>--}}
{{--                        <td>{{ $user['created_at'] }}</td>--}}
{{--                        <td class="text-center">--}}
{{--                            <div class="btn btn-danger btnDelete" data-id="{{ $user['id'] }}">Hapus</div>--}}
{{--                            <div class="btn btn-primary btnUpdate" data-id="{{ $user['id'] }}">Update</div>--}}
{{--                        </td>--}}
{{--                    </tr>--}}
{{--                @endforeach--}}
                </tbody>
            </table>
        </div>
    </div>
    <form id="formDelete" action="" method="post">
        @method('DELETE')
        @csrf
    </form>
    <form id="formUpdate" action="" method="post">
        @csrf
    </form>
    <script>
        let btnDelete = $('.btnDelete')
        let formDelete = $('#formDelete')
        btnDelete.click(function(){
            Swal.fire({
                title: 'Are you sure?',
                text: "You won't be able to revert this!",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Yes, delete it!'
            }).then((result) => {
                if (result.isConfirmed) {
                    formDelete.attr('action', '{{ url('delete') }}/' + $(this).data('id'))
                    formDelete.submit()
                }
            })
        })

        let btnUpdate = $('.btnUpdate')
        let formUpdate = $('#formUpdate')
        btnUpdate.click(function(){
            formUpdate.attr('action', '{{ url('edit') }}/' + $(this).data('id'))
            formUpdate.submit()
        })
    </script>
@endsection